name: Node.js

on:
  push:
    branches: ["main"]
  pull_request:

env:
  NODE_VERSION: "20"

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

  build:
    name: Build Lambda
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Lambda Package
        run: npm run build:lambda

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-deployment
          path: deployment.zip

  deploy_non_prod:
    name: Deploy to Non-Prod
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    environment:
      name: nonprod # yamllint disable-line rule:truthy
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::454953019043:role/MonitoringLambdaDeploymentRole
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-deployment

      - name: Deploy AWS CloudWatch Lambda Function
        run: |
          FUNCTION_NAME="sevvy-monitor-aws-dev"

          if aws lambda get-function --function-name $FUNCTION_NAME >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip
            aws lambda wait function-updated-v2 --function-name $FUNCTION_NAME
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler cloudwatch.handler \
              --runtime nodejs20.x \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api-dev.sevvyai.com,SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/454953019043/sevvy-agent-analysis-queue}"
          else
            echo "Function does not exist, creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::454953019043:role/MonitoringLambdaExecutionRole \
              --handler cloudwatch.handler \
              --zip-file fileb://deployment.zip \
              --timeout 300 \
              --memory-size 512 \
              --description "Sevvy CloudWatch monitoring function for dev environment" \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api-dev.sevvyai.com,SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/454953019043/sevvy-agent-analysis-queue}"
          fi

      - name: Deploy Cloudflare Lambda Function
        run: |
          FUNCTION_NAME="sevvy-monitor-cloudflare-dev"

          if aws lambda get-function --function-name $FUNCTION_NAME >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip
            aws lambda wait function-updated-v2 --function-name $FUNCTION_NAME
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler cloudflare.handler \
              --runtime nodejs20.x \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api-dev.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1,SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/454953019043/sevvy-agent-analysis-queue}"
          else
            echo "Function does not exist, creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::454953019043:role/MonitoringLambdaExecutionRole \
              --handler cloudflare.handler \
              --zip-file fileb://deployment.zip \
              --timeout 300 \
              --memory-size 512 \
              --description "Sevvy Cloudflare monitoring function for dev environment" \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api-dev.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1,SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/454953019043/sevvy-agent-analysis-queue}"
          fi

      - name: Deploy Vercel Lambda Function
        run: |
          FUNCTION_NAME="sevvy-monitor-vercel-dev"

          if aws lambda get-function --function-name $FUNCTION_NAME >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip
            aws lambda wait function-updated-v2 --function-name $FUNCTION_NAME
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler vercel.handler \
              --runtime nodejs20.x \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api-dev.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1,VERCEL_LOGS_S3_BUCKET=sevvy-dev,SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/454953019043/sevvy-agent-analysis-queue}"
          else
            echo "Function does not exist, creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::454953019043:role/MonitoringLambdaExecutionRole \
              --handler vercel.handler \
              --zip-file fileb://deployment.zip \
              --timeout 300 \
              --memory-size 512 \
              --description "Sevvy Vercel monitoring function for dev environment" \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api-dev.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1,VERCEL_LOGS_S3_BUCKET=sevvy-dev,SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/454953019043/sevvy-agent-analysis-queue}"
          fi

  deploy_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: prod # yamllint disable-line rule:truthy
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390240928083:role/MonitoringLambdaDeploymentRole
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-deployment

      - name: Deploy AWS CloudWatch Lambda Function
        run: |
          FUNCTION_NAME="sevvy-monitor-aws-prod"

          if aws lambda get-function --function-name $FUNCTION_NAME >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip
            aws lambda wait function-updated-v2 --function-name $FUNCTION_NAME
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler cloudwatch.handler \
              --runtime nodejs20.x \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api.sevvyai.com}"
          else
            echo "Function does not exist, creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::390240928083:role/MonitoringLambdaExecutionRole \
              --handler cloudwatch.handler \
              --zip-file fileb://deployment.zip \
              --timeout 300 \
              --memory-size 512 \
              --description "Sevvy CloudWatch monitoring function for prod environment" \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api.sevvyai.com}"
          fi

      - name: Deploy Cloudflare Lambda Function
        run: |
          FUNCTION_NAME="sevvy-monitor-cloudflare-prod"

          if aws lambda get-function --function-name $FUNCTION_NAME >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip
            aws lambda wait function-updated-v2 --function-name $FUNCTION_NAME
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler cloudflare.handler \
              --runtime nodejs20.x \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1}"
          else
            echo "Function does not exist, creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::390240928083:role/MonitoringLambdaExecutionRole \
              --handler cloudflare.handler \
              --zip-file fileb://deployment.zip \
              --timeout 300 \
              --memory-size 512 \
              --description "Sevvy Cloudflare monitoring function for prod environment" \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1}"
          fi

      - name: Deploy Vercel Lambda Function
        run: |
          FUNCTION_NAME="sevvy-monitor-vercel-prod"

          if aws lambda get-function --function-name $FUNCTION_NAME >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://deployment.zip
            aws lambda wait function-updated-v2 --function-name $FUNCTION_NAME
            aws lambda update-function-configuration \
              --function-name $FUNCTION_NAME \
              --handler vercel.handler \
              --runtime nodejs20.x \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1,VERCEL_LOGS_S3_BUCKET=sevvy-prod}"
          else
            echo "Function does not exist, creating new function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime nodejs20.x \
              --role arn:aws:iam::390240928083:role/MonitoringLambdaExecutionRole \
              --handler vercel.handler \
              --zip-file fileb://deployment.zip \
              --timeout 300 \
              --memory-size 512 \
              --description "Sevvy Vercel monitoring function for prod environment" \
              --environment Variables="{SEVVY_SERVER_BASE_URL=https://api.sevvyai.com,MAX_MINUTES_PER_RUN=120,SAFETY_MINUTES=1,VERCEL_LOGS_S3_BUCKET=sevvy-prod}"
          fi
